### ISSUE TITLE
Google Pagespeed recommendation - font loading

### ISSUE THREAD

**Issue by navjotjsingh** [adisaktijrs/hexo-theme-minima#14]
As I was checking Pagespeed stats, Google hits me with this warning

![](https://i.imgur.com/z2iHD8l.png)

I believe it should be a simple fix?

**Comment by adisaktijrs** [comment]
Hi, sure we can quick-fix it by adding `font-display: swap;` to `@font-face` on Minima [custom.css file](https://github.com/adisaktijrs/hexo-theme-minima/blob/03f85ae0f9458ad783fb4e2d37d9f92c98df124f/source/css/custom.css).

```css
@font-face {
  font-family: 'DM Serif Display';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/dm-serif-display-v4-latin-regular.eot'); /* IE9 Compat Modes */
  src: local('DM Serif Display Regular'), local('DMSerifDisplay-Regular'),
       url('../fonts/dm-serif-display-v4-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/dm-serif-display-v4-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/dm-serif-display-v4-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('../fonts/dm-serif-display-v4-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/dm-serif-display-v4-latin-regular.svg#DMSerifDisplay') format('svg'); /* Legacy iOS */

  font-display: swap; /* Add font-display */
}

/* inter-regular - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/inter-v2-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('../fonts/inter-v2-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/inter-v2-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/inter-v2-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('../fonts/inter-v2-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/inter-v2-latin-regular.svg#Inter') format('svg'); /* Legacy iOS */

  font-display: swap; /* Add font-display */
}
``` 

Note: It will use/show the system font first before the main font is being loaded. Thank you
