### ISSUE TITLE
Code block

### ISSUE THREAD

**Issue by nerdeveloper** [adisaktijrs/hexo-theme-minima#22]
Hello there, This is a wonderful theme

Please I am trying to write an article  and I am trying to use a particular feature in this theme||

<img width="725" alt="Screenshot 2021-06-16 at 11 56 51" src="https://user-images.githubusercontent.com/26016664/122207512-1eaef500-ce9a-11eb-8d61-cffe5d5d3057.png">

Please how do I activate this section on this theme for code?

**Comment by adisaktijrs** [comment]
Hi, thanks!

You can activate it by following these steps:
- Modify the **_config.yml of your site** (not minima _config.yml) by set the prismjs to **true**. So your file will look like this:
```
highlight:
  enable: false #set it to false
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false #false
  hljs: false
prismjs:
  enable: true #set it to true
  preprocess: true
  line_number: true #optional
  tab_replace: ''
```
- Clear your Hexo cache and run your server, run these comands in your terminal:
```
hexo clean
hexo server
```
- Use the Hexo codeblock syntax when you need to use the code-block in your md file. Example:
```
{% codeblock lang:js %}
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
{% endcodeblock %}
```
