### ISSUE TITLE
Incomplete code highlighting configuration documentation

### ISSUE THREAD

**Issue by markelmencia** [adisaktijrs/hexo-theme-minima#43]
As a complete beginner to Hexo and web-design in general, I found the installation documentation very useful. However, I had some trouble getting the prism.js highlighter to work.

This is the code you provide to get prism.js working:

```yml
highlight:
  enable: false #set it to false
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false #false
  hljs: false
prismjs:
  enable: true #set it to true
  preprocess: true
  line_number: true #optional
  tab_replace: ''
``` 

However, it seems like that is not enough, as you also need to modify the `syntax_highlighter` variable, like this:

```yml
# syntax_highlighter: highligh.js (default Hexo highlighter)
syntax_highlighter: prismjs
``` 

I don't know if that's a given or not (again, I'm very new to this), but I thought it'd be a handful thing to add to the documentation.

Good day!
